CREATE DATABASE T_AutoPecas;

use T_AutoPecas;

CREATE TABLE USUARIOS
(
	IDUSUARIO INT PRIMARY KEY IDENTITY
	,EMAIL VARCHAR(200) NOT NULL UNIQUE
	,SENHA VARCHAR(200) NOT NULL
);

CREATE TABLE FORNECEDORES
(
	IDFORNECEDOR INT PRIMARY KEY IDENTITY
	,CNPJ INT NOT NULL
	,RAZAOSOCIAL VARCHAR (200) NOT NULL UNIQUE
	,NOMEFANTASIA VARCHAR (200) NOT NULL UNIQUE
	,ENDERECO VARCHAR(250) NOT NULL
	,IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS (IDUSUARIO)

);

CREATE TABLE PECAS 
(
	IDPECA INT PRIMARY KEY IDENTITY
	,CODIGOPECA VARCHAR (200) NOT NULL UNIQUE
	,DESCRICAO VARCHAR (200) NOT NULL
	,PESO INT 
	,PRECOCUSTO INT
	,PRECOVENDA INT
	,IDFORNECEDOR INT FOREIGN KEY REFERENCES FORNECEDORES (IDFORNECEDOR)
);
