USE T_AutoPecas;

--DML 
--INSERÇÃO

INSERT USUARIOS (EMAIL, SENHA) VALUES ('R@R.COM', '123');
INSERT USUARIOS (EMAIL, SENHA) VALUES ('T@T.COM', '321');
INSERT USUARIOS (EMAIL, SENHA) VALUES ('H@H.COM', '132');

INSERT FORNECEDORES (CNPJ, RAZAOSOCIAL, NOMEFANTASIA, ENDERECO, IDUSUARIO) VALUES ('987','REFILE MOTORES LTDA','REFILE','RUA SÃO JOÃO, 45, SP',1);
INSERT FORNECEDORES (CNPJ, RAZAOSOCIAL, NOMEFANTASIA, ENDERECO, IDUSUARIO) VALUES ('654','TEOTONIO PNEUS LTDA','TONHAO','AV. DOS ESTADOS, 360, STO. ANDRÉ',2);
INSERT FORNECEDORES (CNPJ, RAZAOSOCIAL, NOMEFANTASIA, ENDERECO, IDUSUARIO) VALUES ('321','HELENA AUTOMÓVEIS LTDA','HELENAUTO','AL. BARÃO DE LIMEIRA, 539', 3);

INSERT PECAS (CODIGOPECA, DESCRICAO, PESO, PRECOCUSTO, PRECOVENDA, IDFORNECEDOR) VALUES ('MOTOR1','MOTOR 300 CAVALOS','100','4800','5200',1);
INSERT PECAS (CODIGOPECA, DESCRICAO, PESO, PRECOCUSTO, PRECOVENDA, IDFORNECEDOR) VALUES ('PNEU2','PNEU ARO 14','1','120','200',2);
INSERT PECAS (CODIGOPECA, DESCRICAO, PESO, PRECOCUSTO, PRECOVENDA, IDFORNECEDOR) VALUES ('EMBREAGEM3','EMBREAGEM','10','250','320',3);

select * from USUARIOS
select * from FORNECEDORES
select * from PECAS
