CREATE DATABASE T_Peoples;

USE T_Peoples;

CREATE TABLE FUNCIONARIOS
(
IDFUNCIONARIOS INT PRIMARY KEY IDENTITY
,NOME VARCHAR(200) NOT NULL 
);

select * from FUNCIONARIOS

ALTER TABLE FUNCIONARIOS
ADD datanascimento date;
